# Generated by Django 2.1.2 on 2019-03-27 21:07

from django.core.management import call_command
from django.db import migrations, models


def load_nationalities(apps, schema_editor):
    call_command('loaddata', 'fixtures/nationalities.json')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RunPython(load_nationalities)
    ]
