# Generated by Django 2.1.2 on 2019-10-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='LastNames',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Rut',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
