# Generated by Django 2.1.2 on 2019-08-27 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='NoExisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 27, 6, 34, 27, 402279)),
        ),
    ]
