# Generated by Django 2.1.2 on 2019-02-20 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='MoreThanOneEdificio',
        ),
    ]
