# Generated by Django 2.1.2 on 2019-03-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0003_adjust_name_on_edificio'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='CotizacionDuration',
            field=models.IntegerField(default=0),
        ),
    ]
