# Generated by Django 2.1.2 on 2019-03-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0004_inmueble_cotizacionduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='CotizacionDuration',
            field=models.IntegerField(),
        ),
    ]
