# Generated by Django 2.1.2 on 2019-08-12 14:43

from django.db import migrations, models
import django.db.models.deletion
import empresas_and_proyectos.models.proyectos


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0005_remove_default_cotizacion_duration_inmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='CompanyPDF',
            field=models.FileField(blank=True, null=True, upload_to=empresas_and_proyectos.models.proyectos.legal_directory_path),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='CompanyWord',
            field=models.FileField(blank=True, null=True, upload_to=empresas_and_proyectos.models.proyectos.legal_directory_path),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='CounterPDF',
            field=models.FileField(blank=True, null=True, upload_to=empresas_and_proyectos.models.proyectos.legal_directory_path),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='CounterWord',
            field=models.FileField(blank=True, null=True, upload_to=empresas_and_proyectos.models.proyectos.legal_directory_path),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='CreditPDF',
            field=models.FileField(blank=True, null=True, upload_to=empresas_and_proyectos.models.proyectos.legal_directory_path),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='CreditWord',
            field=models.FileField(blank=True, null=True, upload_to=empresas_and_proyectos.models.proyectos.legal_directory_path),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='EtapaStateID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etapastate_proyecto', to='empresas_and_proyectos.EtapaState'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='MarketingExcel',
            field=models.FileField(blank=True, null=True, upload_to=empresas_and_proyectos.models.proyectos.marketing_directory_path),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='MarketingPDF',
            field=models.FileField(blank=True, null=True, upload_to=empresas_and_proyectos.models.proyectos.marketing_directory_path),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='MarketingProjectExcel',
            field=models.FileField(blank=True, null=True, upload_to=empresas_and_proyectos.models.proyectos.marketing_directory_path),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='Address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='BorradorPromesaState',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_borrador_promesa_proyecto', to='empresas_and_proyectos.BorradorPromesaState'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ComunaID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comuna_proyecto', to='common.Comuna'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ConstructoraID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constructora_proyecto', to='empresas_and_proyectos.Constructora'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='CotizacionDuration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='GuaranteeAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='IngresoComisionesState',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_ingreso_comisiones_proyecto', to='empresas_and_proyectos.IngresoComisionesState'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='InmobiliariaID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inmobiliaria_proyecto', to='empresas_and_proyectos.Inmobiliaria'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='PlanMediosState',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_plan_medios_proyecto', to='empresas_and_proyectos.PlanMediosState'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ProyectoApprovalState',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_aprobacion_proyecto', to='empresas_and_proyectos.ProyectoApprovalState'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='Symbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
