# Generated by Django 2.1.2 on 2019-08-17 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0006_auto_20190812_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproyecto',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_proyecto', to='users.User'),
        ),
    ]
