# Generated by Django 2.1.2 on 2019-08-20 15:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
import empresas_and_proyectos.models.project_documents


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_nationality'),
        ('empresas_and_proyectos', '0007_auto_20190817_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Document', models.FileField(blank=True, null=True, upload_to=empresas_and_proyectos.models.project_documents.document_directory_path)),
                ('DocumentType', models.CharField(max_length=50)),
                ('State', models.CharField(choices=[('to_confirm', 'To Confirm'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='to_confirm', max_length=50)),
                ('CreateAt', models.DateTimeField(default=datetime.datetime(2019, 8, 20, 11, 32, 49, 819051))),
                ('Poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_document', to='users.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='CompanyPDF',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='CompanyWord',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='CounterPDF',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='CounterWord',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='CreditPDF',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='CreditWord',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='MarketingExcel',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='MarketingPDF',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='MarketingProjectExcel',
        ),
        migrations.AlterField(
            model_name='userproyecto',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='Documents',
            field=models.ManyToManyField(related_name='document_project', to='empresas_and_proyectos.ProjectDocument'),
        ),
    ]
