# Generated by Django 2.1.2 on 2019-08-20 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0008_auto_20190820_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='ProjectID',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 20, 11, 49, 49, 484873)),
        ),
    ]
