# Generated by Django 2.1.2 on 2019-08-22 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0009_auto_20190820_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='EntregaInmediata',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 22, 0, 46, 13, 580078)),
        ),
    ]
