# Generated by Django 2.1.2 on 2019-08-22 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0010_auto_20190822_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 22, 22, 21, 16, 107798)),
        ),
    ]
