# Generated by Django 2.1.2 on 2019-08-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0002_auto_20190827_0634'),
        ('empresas_and_proyectos', '0011_auto_20190822_2221'),
    ]

    operations = [
    ]
