# Generated by Django 2.1.2 on 2019-08-30 11:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0012_merge_20190830_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='orientation',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 30, 11, 12, 7, 60514, tzinfo=utc)),
        ),
    ]
