# Generated by Django 2.1.2 on 2019-08-31 15:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0013_auto_20190830_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 31, 15, 35, 2, 477089, tzinfo=utc)),
        ),
    ]
