# Generated by Django 2.1.2 on 2019-09-01 09:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0014_auto_20190831_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueblestate',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmuebletype',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipologia',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 1, 9, 14, 34, 433132, tzinfo=utc)),
        ),
    ]
