# Generated by Django 2.1.2 on 2019-09-01 09:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0015_auto_20190901_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueblestate',
            name='Description',
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 1, 9, 32, 52, 848254, tzinfo=utc)),
        ),
    ]
