# Generated by Django 2.1.2 on 2019-10-01 14:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0016_auto_20190901_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 1, 14, 5, 48, 715282, tzinfo=utc)),
        ),
    ]
