# Generated by Django 2.1.2 on 2019-10-08 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0017_auto_20191001_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 8, 16, 55, 0, 244814, tzinfo=utc)),
        ),
    ]
