# Generated by Django 2.1.2 on 2019-10-09 07:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0018_auto_20191008_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 9, 7, 56, 50, 873887, tzinfo=utc)),
        ),
    ]
