# Generated by Django 2.1.2 on 2019-10-10 09:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0019_auto_20191009_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 10, 9, 19, 25, 547313, tzinfo=utc)),
        ),
    ]
