# Generated by Django 2.1.2 on 2019-10-14 17:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0020_auto_20191010_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 14, 17, 48, 44, 354545, tzinfo=utc)),
        ),
    ]
