# Generated by Django 2.1.2 on 2019-10-15 02:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0021_auto_20191015_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 15, 2, 51, 1, 622649, tzinfo=utc)),
        ),
    ]
