# Generated by Django 2.1.2 on 2019-10-25 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0022_auto_20191015_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 25, 13, 47, 32, 172361, tzinfo=utc)),
        ),
    ]
