# Generated by Django 2.1.2 on 2019-10-25 18:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0024_auto_20191026_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 25, 18, 0, 56, 40021, tzinfo=utc)),
        ),
    ]
