# Generated by Django 2.1.2 on 2019-10-31 06:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0025_auto_20191026_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 6, 18, 35, 166501, tzinfo=utc)),
        ),
    ]
