# Generated by Django 2.1.2 on 2019-11-07 15:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0027_auto_20191031_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 7, 15, 13, 50, 378110, tzinfo=utc)),
        ),
    ]
