# Generated by Django 2.1.2 on 2019-11-08 17:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0029_auto_20191108_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 17, 15, 7, 870093, tzinfo=utc)),
        ),
    ]
