# Generated by Django 2.1.2 on 2019-01-30 16:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas_and_proyectos', '__first__'),
        ('users', '__first__'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antiquity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AntiquityID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CivilStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CivilStatusID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.User')),
                ('Address', models.CharField(max_length=150)),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('LastModificationDate', models.DateTimeField(auto_now=True)),
                ('Nationality', models.CharField(blank=True, max_length=40, null=True)),
                ('BirthDate', models.DateTimeField(blank=True, null=True)),
                ('Occupation', models.CharField(blank=True, max_length=40, null=True)),
                ('Position', models.CharField(blank=True, max_length=40, null=True)),
                ('Carga', models.IntegerField(blank=True, null=True)),
                ('Salary', models.IntegerField(blank=True, null=True)),
                ('TotalPatrimony', models.IntegerField(blank=True, null=True)),
                ('IsDefinitiveResidence', models.BooleanField(default=False)),
                ('AntiquityID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antiguedad_laboral_cliente', to='ventas.Antiquity')),
                ('CivilStatusID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_civil_cliente', to='ventas.CivilStatus')),
                ('ComunaID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comuna_cliente', to='common.Comuna')),
            ],
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='ClienteContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(max_length=60)),
                ('ContactInfoTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.ContactInfoType')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConditionID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMethodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactMethodTypeID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ContractMarriageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractMarriageTypeID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CotizacionID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Folio', models.IntegerField(default=0)),
                ('IsNotInvestment', models.BooleanField(default=False)),
                ('PaymentFirmaEscritura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentInstitucionFinanciera', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ClienteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_cotizacion', to='ventas.Cliente')),
                ('ContactMethodTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medio_contacto_cotizacion', to='ventas.ContactMethodType')),
            ],
        ),
        migrations.CreateModel(
            name='CotizacionInmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('CotizacionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Cotizacion')),
                ('InmuebleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas_and_proyectos.Inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='CotizacionState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CotizacionStateID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CotizacionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CotizacionTypeID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CounterFolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.IntegerField(default=1)),
                ('ProyectoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_contador', to='empresas_and_proyectos.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CuotaID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpleadorID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('RazonSocial', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('ClienteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_empleador', to='ventas.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaCompradora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpresaCompradoraID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('RazonSocial', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('Rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('Address', models.CharField(blank=True, max_length=150, null=True)),
                ('ClienteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_cliente', to='ventas.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='FindingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FindingTypeID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GenreID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PayType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PayTypeID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoFinanciero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductoFinancieroID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=20)),
                ('Value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReservaID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Folio', models.IntegerField(default=0)),
                ('IsNotInvestment', models.BooleanField(default=False)),
                ('PaymentFirmaPromesa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentFirmaEscritura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentInstitucionFinanciera', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('DateFirmaPromesa', models.DateTimeField(blank=True, null=True)),
                ('ValueProductoFinanciero', models.IntegerField(blank=True, null=True)),
                ('ClienteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_reserva', to='ventas.Cliente')),
                ('CodeudorID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codeudor_reserva', to='ventas.Cliente')),
                ('ConditionID', models.ManyToManyField(related_name='condition_reserva', to='ventas.Condition')),
                ('ContactMethodTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medio_contacto_reserva', to='ventas.ContactMethodType')),
                ('CuotaID', models.ManyToManyField(related_name='cuota_reserva', to='ventas.Cuota')),
                ('EmpresaCompradoraID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_compradora_reserva', to='ventas.EmpresaCompradora')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaInmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('InmuebleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas_and_proyectos.Inmueble')),
                ('ReservaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Reserva')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReservaStateID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Subsidio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubsidioID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Ahorro', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='VentaLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VentaLogID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('VentaID', models.UUIDField()),
                ('Comment', models.CharField(blank=True, max_length=150, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('DocumentCotizacion', models.FileField(blank=True, null=True, upload_to='DocumentVentas')),
                ('DocumentOferta', models.FileField(blank=True, null=True, upload_to='DocumentVentas')),
                ('DocumentFichaPreAprobacion', models.FileField(blank=True, null=True, upload_to='DocumentVentas')),
                ('DocumentScoring', models.FileField(blank=True, null=True, upload_to='DocumentVentas')),
                ('DocumentCertificadoMatrimonio', models.FileField(blank=True, null=True, upload_to='DocumentVentas')),
                ('DocumentConstitucionSociedad', models.FileField(blank=True, null=True, upload_to='DocumentVentas')),
                ('DocumentPagoGarantia', models.FileField(blank=True, null=True, upload_to='DocumentVentas')),
                ('DocumentFotocopiaCarnet', models.FileField(blank=True, null=True, upload_to='DocumentVentas')),
                ('DocumentLiquidacion1', models.FileField(blank=True, null=True, upload_to='DocumentVentas')),
                ('DocumentLiquidacion2', models.FileField(blank=True, null=True, upload_to='DocumentVentas')),
                ('DocumentLiquidacion3', models.FileField(blank=True, null=True, upload_to='DocumentVentas')),
                ('DocumentCotizacionAFP', models.FileField(blank=True, null=True, upload_to='DocumentVentas')),
                ('ClienteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_historial_venta', to='ventas.Cliente')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_historial_venta', to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='VentaLogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VentaLogTypeID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=20)),
                ('MaximunDays', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='ventalog',
            name='VentaLogTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.VentaLogType'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='InmuebleID',
            field=models.ManyToManyField(related_name='inmuebles_reserva', through='ventas.ReservaInmueble', to='empresas_and_proyectos.Inmueble'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='PayTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_pago_reserva', to='ventas.PayType'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='ProyectoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_reserva', to='empresas_and_proyectos.Proyecto'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='ReservaStateID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_reserva', to='ventas.ReservaState'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='VendedorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_reserva', to='users.User'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='CotizacionStateID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_cotizacion', to='ventas.CotizacionState'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='CotizacionTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_cotizacion', to='ventas.CotizacionType'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='CotizadorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizador_cotizacion', to='users.User'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='CuotaID',
            field=models.ManyToManyField(related_name='cuotas_cotizacion', to='ventas.Cuota'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='InmuebleID',
            field=models.ManyToManyField(related_name='inmuebles_cotizacion', through='ventas.CotizacionInmueble', to='empresas_and_proyectos.Inmueble'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='ProyectoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_cotizacion', to='empresas_and_proyectos.Proyecto'),
        ),
        migrations.AddField(
            model_name='clienteproyecto',
            name='FindingTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.FindingType'),
        ),
        migrations.AddField(
            model_name='clienteproyecto',
            name='ProyectoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas_and_proyectos.Proyecto'),
        ),
        migrations.AddField(
            model_name='clienteproyecto',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ContactInfo',
            field=models.ManyToManyField(related_name='contacto_cliente', through='ventas.ClienteContactInfo', to='common.ContactInfoType'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ContractMarriageTypeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_contrato_matrimonio_cliente', to='ventas.ContractMarriageType'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_cliente', to='users.User'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='GenreID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genero_cliente', to='ventas.Genre'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='LastModifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_modifier_cliente', to='users.User'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Proyecto',
            field=models.ManyToManyField(related_name='finding_way', through='ventas.ClienteProyecto', to='empresas_and_proyectos.Proyecto'),
        ),
    ]
