# Generated by Django 2.1.2 on 2019-02-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='Folio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Folio',
            field=models.TextField(default=''),
        ),
    ]
