# Generated by Django 2.1.2 on 2019-02-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_change_folio_int_to_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='Folio',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Folio',
            field=models.CharField(default='', max_length=50),
        ),
    ]
