# Generated by Django 2.1.2 on 2019-02-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_change_folio_text_to_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='Folio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Folio',
            field=models.CharField(max_length=50),
        ),
    ]
