# Generated by Django 2.1.2 on 2019-03-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_auto_20190222_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Occupation',
            new_name='Ocupation',
        ),
    ]
