# Generated by Django 2.1.2 on 2019-03-06 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0003_adjust_name_on_edificio'),
        ('ventas', '0007_delete_genre_civil_status_contract_marriage_type_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventalog',
            name='ProyectoID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_historial_venta', to='empresas_and_proyectos.Proyecto'),
        ),
    ]
