# Generated by Django 2.1.2 on 2019-03-06 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_ventalog_proyectoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='BirthDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='BirthDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Carga',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='CivilStatus',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ContractMarriageType',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Ocupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='Salary',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='TotalPatrimony',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ventalog',
            name='ProyectoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_historial_venta', to='empresas_and_proyectos.Proyecto'),
        ),
    ]
