# Generated by Django 2.1.2 on 2019-03-08 13:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0003_adjust_name_on_edificio'),
        ('ventas', '0009_adjust_cliente_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OfertaID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('OfertaState', models.CharField(max_length=100)),
                ('AprobacionInmobiliariaState', models.CharField(max_length=100)),
                ('PreAprobacionCreditoState', models.CharField(max_length=100)),
                ('RecepcionGarantiaState', models.CharField(max_length=100)),
                ('PaymentFirmaPromesa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentFirmaEscritura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentInstitucionFinanciera', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('DateFirmaPromesa', models.DateTimeField(blank=True, null=True)),
                ('ValueProductoFinanciero', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='BirthDate',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='oferta',
            name='ClienteID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_oferta', to='ventas.Cliente'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='ContactMethodTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medio_contacto_oferta', to='ventas.ContactMethodType'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='PayTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_pago_oferta', to='ventas.PayType'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='ProyectoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_oferta', to='empresas_and_proyectos.Proyecto'),
        ),
    ]
