# Generated by Django 2.1.2 on 2019-03-08 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('ventas', '0010_create_model_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='CodeudorID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codeudor_oferta', to='ventas.Cliente'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='EmpresaCompradoraID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_compradora_oferta', to='ventas.EmpresaCompradora'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='VendedorID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_oferta', to='users.User'),
        ),
    ]
