# Generated by Django 2.1.2 on 2019-03-08 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_add_more_fields_to_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='Folio',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='CodeudorID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codeudor_oferta', to='ventas.Cliente'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='EmpresaCompradoraID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_compradora_oferta', to='ventas.EmpresaCompradora'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='VendedorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_oferta', to='users.User'),
        ),
    ]
