# Generated by Django 2.1.2 on 2019-03-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_add_folio_to_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='IsImportant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='Folio',
            field=models.CharField(max_length=50),
        ),
    ]
