# Generated by Django 2.1.2 on 2019-03-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_add_field_is_important_to_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventalogtype',
            name='Name',
            field=models.CharField(max_length=60),
        ),
    ]
