# Generated by Django 2.1.2 on 2019-03-12 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_adjust_length_name_venta_log_type_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 12, 8, 57, 26, 520534)),
        ),
    ]
