# Generated by Django 2.1.2 on 2019-03-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_oferta_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
