# Generated by Django 2.1.2 on 2019-03-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0018_add_blank_to_result_pre_aprobacion_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='IsApproveInmobiliaria',
            field=models.BooleanField(default=False),
        ),
    ]
