# Generated by Django 2.1.2 on 2019-03-19 20:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0021_add_blank_null_to birth_date_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatrimonyID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('RealState', models.PositiveIntegerField(default=0)),
                ('Vehicle', models.PositiveIntegerField(default=0)),
                ('DownPayment', models.PositiveIntegerField(default=0)),
                ('Other', models.PositiveIntegerField(default=0)),
                ('CreditCard', django.contrib.postgres.fields.jsonb.JSONField()),
                ('CreditoConsumo', django.contrib.postgres.fields.jsonb.JSONField()),
                ('PrestamoEmpleador', django.contrib.postgres.fields.jsonb.JSONField()),
                ('CreditoComercio', django.contrib.postgres.fields.jsonb.JSONField()),
                ('DeudaIndirecta', django.contrib.postgres.fields.jsonb.JSONField()),
                ('AnotherCredit', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ClienteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_patrimony', to='ventas.Cliente')),
            ],
        ),
    ]
