# Generated by Django 2.1.2 on 2019-03-20 16:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0022_model_patrimony'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimony',
            name='CreditoHipotecario',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
    ]
