# Generated by Django 2.1.2 on 2019-03-25 16:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0023_patrimony_creditohipotecario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='AntiquityID',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='DateFirmaPromesa',
            field=models.DateTimeField(blank=True,null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='PaymentFirmaPromesa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Antiquity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='CreditoHipotecario',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.DeleteModel(
            name='Antiquity',
        ),
    ]
