# Generated by Django 2.1.2 on 2019-03-28 14:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0024_remove_antiquity_model_refactor_cliente_reserva_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
    ]
