# Generated by Django 2.1.2 on 2019-04-04 16:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0027_alter_decimal_places_amount_cuota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='empleador',
            name='Extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
