# Generated by Django 2.1.2 on 2019-04-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0028_default_dict_to_extra_cliente_add_extra_to_empleador'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='IsCompany',
            field=models.BooleanField(default=False),
        ),
    ]
