# Generated by Django 2.1.2 on 2019-05-07 13:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0029_cliente_iscompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
