# Generated by Django 2.1.2 on 2019-05-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0030_add_null_to_extra_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventalog',
            name='Folio',
            field=models.CharField(default='', max_length=50),
        ),
    ]
