# Generated by Django 2.1.2 on 2019-05-28 17:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0005_remove_default_cotizacion_duration_inmueble'),
        ('users', '0002_nationality'),
        ('ventas', '0031_ventalog_folio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PromesaID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Folio', models.CharField(max_length=50)),
                ('PromesaState', models.CharField(max_length=100)),
                ('DocumentFirmaComprador', models.FileField(blank=True, null=True, upload_to='DocumentVentas')),
                ('DocumentPaymentForm', models.FileField(blank=True, null=True, upload_to='DocumentVentas')),
                ('DateEnvioPromesa', models.DateTimeField(blank=True, null=True)),
                ('DateRegresoPromesa', models.DateTimeField(blank=True, null=True)),
                ('DateLegalizacionPromesa', models.DateTimeField(blank=True, null=True)),
                ('DateEnvioCopias', models.DateTimeField(blank=True, null=True)),
                ('PaymentFirmaPromesa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentFirmaEscritura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentInstitucionFinanciera', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ClienteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_promesa', to='ventas.Cliente')),
                ('CodeudorID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codeudor_promesa', to='ventas.Cliente')),
                ('PayTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_pago_promesa', to='ventas.PayType')),
                ('ProyectoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_promesa', to='empresas_and_proyectos.Proyecto')),
                ('VendedorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_promesa', to='users.User')),
            ],
        ),
    ]
