# Generated by Django 2.1.2 on 2019-05-28 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0005_remove_default_cotizacion_duration_inmueble'),
        ('ventas', '0032_promesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromesaInmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('InmuebleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas_and_proyectos.Inmueble')),
                ('PromesaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Promesa')),
            ],
        ),
    ]
