# Generated by Django 2.1.2 on 2019-05-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0005_remove_default_cotizacion_duration_inmueble'),
        ('ventas', '0033_promesainmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='promesa',
            name='InmuebleID',
            field=models.ManyToManyField(related_name='inmuebles_promesa', through='ventas.PromesaInmueble', to='empresas_and_proyectos.Inmueble'),
        ),
    ]
