# Generated by Django 2.1.2 on 2019-06-06 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0034_promesa_inmuebleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='promesa',
            name='PromesaModified',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promesa_modificada', to='ventas.Promesa'),
        ),
    ]
