# Generated by Django 2.1.2 on 2019-06-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0035_promesa_promesamodified'),
    ]

    operations = [
        migrations.AddField(
            model_name='promesa',
            name='IsOfficial',
            field=models.BooleanField(default=True),
        ),
    ]
