# Generated by Django 2.1.2 on 2019-06-18 22:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0005_remove_default_cotizacion_duration_inmueble'),
        ('ventas', '0036_promesa_isofficial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacturaID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Number', models.IntegerField()),
                ('Value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('DateEnvio', models.DateTimeField(blank=True, null=True)),
                ('DatePayment', models.DateTimeField(blank=True, null=True)),
                ('FacturaState', models.CharField(max_length=100)),
                ('InmobiliariaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmobiliaria_factura', to='empresas_and_proyectos.Inmobiliaria')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaInmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FolioVenta', models.CharField(max_length=50)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Comision', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Tipo', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('FacturaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura_factura_inmueble', to='ventas.Factura')),
                ('InmuebleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmueble_factura_inmueble', to='empresas_and_proyectos.Inmueble')),
                ('ProyectoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_factura_inmueble', to='empresas_and_proyectos.Proyecto')),
            ],
        ),
        migrations.AlterField(
            model_name='promesa',
            name='PromesaModified',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promesa_modificada', to='ventas.Promesa'),
        ),
        migrations.AddField(
            model_name='factura',
            name='InmuebleID',
            field=models.ManyToManyField(related_name='inmuebles_factura', through='ventas.FacturaInmueble', to='empresas_and_proyectos.Inmueble'),
        ),
        migrations.AddField(
            model_name='factura',
            name='ProyectoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_factura', to='empresas_and_proyectos.Proyecto'),
        ),
    ]
