# Generated by Django 2.1.2 on 2019-06-20 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0005_remove_default_cotizacion_duration_inmueble'),
        ('ventas', '0037_add_model_factura_and_factura_inmueble'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionInmobiliaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PromesaFirmada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('EscrituraFirmada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('CierreGestion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('InmobiliariaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comision_inmobiliaria', to='empresas_and_proyectos.Inmobiliaria')),
                ('ProyectoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_comision_inmobiliaria', to='empresas_and_proyectos.Proyecto')),
            ],
        ),
    ]
