# Generated by Django 2.1.2 on 2019-06-20 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0038_comisioninmobiliaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comisioninmobiliaria',
            name='InmobiliariaID',
        ),
    ]
