# Generated by Django 2.1.2 on 2019-06-20 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0039_remove_comisioninmobiliaria_inmobiliariaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturainmueble',
            name='FacturaID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura_factura_inmueble', to='ventas.Factura'),
        ),
    ]
