# Generated by Django 2.1.2 on 2019-08-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0040_add_null_to_factura_id_factura_inmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='comisioninmobiliaria',
            name='NoExisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comisioninmobiliaria',
            name='State',
            field=models.CharField(choices=[('to_confirm', 'To Confirm'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='to_confirm', max_length=50),
        ),
    ]
