# Generated by Django 2.1.2 on 2019-10-01 14:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_nationality'),
        ('ventas', '0041_auto_20190831_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InterestedTypeID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='PayType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paytype_cotizacion', to='ventas.PayType'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='Vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_cotizacion', to='users.User'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='Observacion',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clienteproyecto',
            name='FindingTypeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.FindingType'),
        ),
        migrations.AddField(
            model_name='clienteproyecto',
            name='InterestedTypeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.InterestedType'),
        ),
    ]
