# Generated by Django 2.1.2 on 2019-10-08 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0042_auto_20191001_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteproyecto',
            name='InterestedTypeID',
        ),
        migrations.AlterField(
            model_name='documentventa',
            name='Folio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empleador',
            name='ClienteID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_empleador', to='ventas.Cliente'),
        ),
        migrations.AlterField(
            model_name='empresacompradora',
            name='ClienteID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_cliente', to='ventas.Cliente'),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='ClienteID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_patrimony', to='ventas.Cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='ClienteID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_reserva', to='ventas.Cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='ConditionID',
            field=models.ManyToManyField(blank=True, null=True, related_name='condition_reserva', to='ventas.Condition'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='ContactMethodTypeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medio_contacto_reserva', to='ventas.ContactMethodType'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='CuotaID',
            field=models.ManyToManyField(blank=True, null=True, related_name='cuota_reserva', to='ventas.Cuota'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Folio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='InmuebleID',
            field=models.ManyToManyField(blank=True, null=True, related_name='inmuebles_reserva', through='ventas.ReservaInmueble', to='empresas_and_proyectos.Inmueble'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='PayTypeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_pago_reserva', to='ventas.PayType'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='PaymentFirmaEscritura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='PaymentFirmaPromesa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='ReservaStateID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_reserva', to='ventas.ReservaState'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='VendedorID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_reserva', to='users.User'),
        ),
        migrations.AlterField(
            model_name='ventalog',
            name='ClienteID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_historial_venta', to='ventas.Cliente'),
        ),
        migrations.AlterField(
            model_name='ventalog',
            name='Folio',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ventalog',
            name='UserID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_historial_venta', to='users.User'),
        ),
        migrations.AlterField(
            model_name='ventalog',
            name='VentaLogTypeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.VentaLogType'),
        ),
    ]
