# Generated by Django 2.1.2 on 2019-10-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0043_auto_20191008_2355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterestedType',
        ),
        migrations.AddField(
            model_name='patrimony',
            name='Deposits',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
