# Generated by Django 2.1.2 on 2019-10-10 09:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0044_auto_20191009_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimony',
            name='AnotherCredit',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='CreditCard',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='CreditoComercio',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='CreditoConsumo',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='CreditoHipotecario',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='DeudaIndirecta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='DownPayment',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='Other',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='PrestamoEmpleador',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='RealState',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patrimony',
            name='Vehicle',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
