# Generated by Django 2.1.2 on 2019-10-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0045_auto_20191010_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimony',
            name='Rent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
