# Generated by Django 2.1.2 on 2019-10-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0046_patrimony_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleador',
            name='RazonSocial',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
