# Generated by Django 2.1.2 on 2019-10-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0047_auto_20191015_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='GiroEmpresa',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ReprenetanteLegal',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
