# Generated by Django 2.1.2 on 2019-10-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0048_auto_20191025_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentventa',
            name='Document2DAI',
            field=models.FileField(blank=True, null=True, upload_to='DocumentVentas'),
        ),
        migrations.AddField(
            model_name='documentventa',
            name='Document6IVA',
            field=models.FileField(blank=True, null=True, upload_to='DocumentVentas'),
        ),
        migrations.AddField(
            model_name='documentventa',
            name='DocumentAcredittacionAhorros',
            field=models.FileField(blank=True, null=True, upload_to='DocumentVentas'),
        ),
        migrations.AddField(
            model_name='documentventa',
            name='DocumentAcredittacionDeudas',
            field=models.FileField(blank=True, null=True, upload_to='DocumentVentas'),
        ),
        migrations.AddField(
            model_name='documentventa',
            name='DocumentBalancesTimbrados',
            field=models.FileField(blank=True, null=True, upload_to='DocumentVentas'),
        ),
        migrations.AddField(
            model_name='documentventa',
            name='DocumentCarpetaTributaria',
            field=models.FileField(blank=True, null=True, upload_to='DocumentVentas'),
        ),
        migrations.AddField(
            model_name='documentventa',
            name='DocumentCertificadoSociedad',
            field=models.FileField(blank=True, null=True, upload_to='DocumentVentas'),
        ),
        migrations.AddField(
            model_name='documentventa',
            name='DocumentTituloProfesional',
            field=models.FileField(blank=True, null=True, upload_to='DocumentVentas'),
        ),
    ]
