# Generated by Django 2.1.2 on 2019-10-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0049_auto_20191026_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Education',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
