# Generated by Django 2.1.2 on 2019-10-31 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0050_cliente_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Education',
        ),
    ]
