# Generated by Django 2.1.2 on 2019-10-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0051_remove_cliente_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='AhorroPlus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='AhorroPlus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promesa',
            name='AhorroPlus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='AhorroPlus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
