# Generated by Django 2.1.2 on 2019-11-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0052_auto_20191031_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='preaprobacioncredito',
            name='DocumentCredit',
            field=models.FileField(blank=True, null=True, upload_to='PreAprobacionCredito'),
        ),
        migrations.AddField(
            model_name='preaprobacioncredito',
            name='Observacion',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='preaprobacioncredito',
            name='Result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
