# Generated by Django 2.1.2 on 2019-11-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0053_auto_20191107_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preaprobacioncredito',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
