# Generated by Django 2.1.2 on 2019-11-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0054_auto_20191108_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='IsApprove',
            field=models.BooleanField(default=False),
        ),
    ]
