# Generated by Django 2.1.2 on 2019-02-20 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinmueble',
            name='InmuebleID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
