# Generated by Django 2.1.2 on 2019-03-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_remove_historicalproyecto_morethanoneedificio'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinmueble',
            name='CotizacionDuration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
