# Generated by Django 2.1.2 on 2019-08-12 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_historicalinmueble_cotizacionduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproyecto',
            name='Address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproyecto',
            name='BorradorPromesaState',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historical_estado_borrador_promesa_proyecto', to='empresas_and_proyectos.BorradorPromesaState'),
        ),
        migrations.AlterField(
            model_name='historicalproyecto',
            name='ComunaID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historical_comuna_proyecto', to='common.Comuna'),
        ),
        migrations.AlterField(
            model_name='historicalproyecto',
            name='ConstructoraID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historical_constructora_proyecto', to='empresas_and_proyectos.Constructora'),
        ),
        migrations.AlterField(
            model_name='historicalproyecto',
            name='CotizacionDuration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproyecto',
            name='GuaranteeAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproyecto',
            name='IngresoComisionesState',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historical_estado_ingreso_comisiones_proyecto', to='empresas_and_proyectos.IngresoComisionesState'),
        ),
        migrations.AlterField(
            model_name='historicalproyecto',
            name='InmobiliariaID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historical_inmobiliaria_proyecto', to='empresas_and_proyectos.Inmobiliaria'),
        ),
        migrations.AlterField(
            model_name='historicalproyecto',
            name='PlanMediosState',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historical_estado_plan_medios_proyecto', to='empresas_and_proyectos.PlanMediosState'),
        ),
        migrations.AlterField(
            model_name='historicalproyecto',
            name='Symbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
